apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-wordpress
spec:
  storageClassName: manual
  accessModes:
     - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: "/opt/netdev/wordpress"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
